//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MultiSeguroViagem.Service.RedeCardProd {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: O elemento de extensão WSDL opcional 'PolicyReference' do espaço para nome 'http://schemas.xmlsoap.org/ws/2004/09/policy' não foi tratado.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IKomerciWcf", Namespace="http://tempuri.org/")]
    public partial class KomerciWcf : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAuthorizedCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAuthorizedDebitOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoidTransactionTIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmTxnTIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KomerciWcf() {
            this.Url = global::MultiSeguroViagem.Service.Properties.Settings.Default.MultiSeguroViagem_Service_RedeCardProd_KomerciWcf;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAuthorizedCreditCompletedEventHandler GetAuthorizedCreditCompleted;
        
        /// <remarks/>
        public event GetAuthorizedDebitCompletedEventHandler GetAuthorizedDebitCompleted;
        
        /// <remarks/>
        public event VoidTransactionTIDCompletedEventHandler VoidTransactionTIDCompleted;
        
        /// <remarks/>
        public event ConfirmTxnTIDCompletedEventHandler ConfirmTxnTIDCompleted;
        
        /// <remarks/>
        public event QueryCompletedEventHandler QueryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKomerciWcf/GetAuthorizedCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CreditAuthorizationResponse GetAuthorizedCredit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GetAuthorizedCredit request) {
            object[] results = this.Invoke("GetAuthorizedCredit", new object[] {
                        request});
            return ((CreditAuthorizationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorizedCreditAsync(GetAuthorizedCredit request) {
            this.GetAuthorizedCreditAsync(request, null);
        }
        
        /// <remarks/>
        public void GetAuthorizedCreditAsync(GetAuthorizedCredit request, object userState) {
            if ((this.GetAuthorizedCreditOperationCompleted == null)) {
                this.GetAuthorizedCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizedCreditOperationCompleted);
            }
            this.InvokeAsync("GetAuthorizedCredit", new object[] {
                        request}, this.GetAuthorizedCreditOperationCompleted, userState);
        }
        
        private void OnGetAuthorizedCreditOperationCompleted(object arg) {
            if ((this.GetAuthorizedCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorizedCreditCompleted(this, new GetAuthorizedCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKomerciWcf/GetAuthorizedDebit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Authorization GetAuthorizedDebit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GetAuthorizedDebit request) {
            object[] results = this.Invoke("GetAuthorizedDebit", new object[] {
                        request});
            return ((Authorization)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorizedDebitAsync(GetAuthorizedDebit request) {
            this.GetAuthorizedDebitAsync(request, null);
        }
        
        /// <remarks/>
        public void GetAuthorizedDebitAsync(GetAuthorizedDebit request, object userState) {
            if ((this.GetAuthorizedDebitOperationCompleted == null)) {
                this.GetAuthorizedDebitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizedDebitOperationCompleted);
            }
            this.InvokeAsync("GetAuthorizedDebit", new object[] {
                        request}, this.GetAuthorizedDebitOperationCompleted, userState);
        }
        
        private void OnGetAuthorizedDebitOperationCompleted(object arg) {
            if ((this.GetAuthorizedDebitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorizedDebitCompleted(this, new GetAuthorizedDebitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKomerciWcf/VoidTransactionTID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Confirmation VoidTransactionTID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] VoidTransactionTID request) {
            object[] results = this.Invoke("VoidTransactionTID", new object[] {
                        request});
            return ((Confirmation)(results[0]));
        }
        
        /// <remarks/>
        public void VoidTransactionTIDAsync(VoidTransactionTID request) {
            this.VoidTransactionTIDAsync(request, null);
        }
        
        /// <remarks/>
        public void VoidTransactionTIDAsync(VoidTransactionTID request, object userState) {
            if ((this.VoidTransactionTIDOperationCompleted == null)) {
                this.VoidTransactionTIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoidTransactionTIDOperationCompleted);
            }
            this.InvokeAsync("VoidTransactionTID", new object[] {
                        request}, this.VoidTransactionTIDOperationCompleted, userState);
        }
        
        private void OnVoidTransactionTIDOperationCompleted(object arg) {
            if ((this.VoidTransactionTIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoidTransactionTIDCompleted(this, new VoidTransactionTIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKomerciWcf/ConfirmTxnTID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Authorization ConfirmTxnTID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ConfirmTxnTID request) {
            object[] results = this.Invoke("ConfirmTxnTID", new object[] {
                        request});
            return ((Authorization)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmTxnTIDAsync(ConfirmTxnTID request) {
            this.ConfirmTxnTIDAsync(request, null);
        }
        
        /// <remarks/>
        public void ConfirmTxnTIDAsync(ConfirmTxnTID request, object userState) {
            if ((this.ConfirmTxnTIDOperationCompleted == null)) {
                this.ConfirmTxnTIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmTxnTIDOperationCompleted);
            }
            this.InvokeAsync("ConfirmTxnTID", new object[] {
                        request}, this.ConfirmTxnTIDOperationCompleted, userState);
        }
        
        private void OnConfirmTxnTIDOperationCompleted(object arg) {
            if ((this.ConfirmTxnTIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmTxnTIDCompleted(this, new ConfirmTxnTIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IKomerciWcf/Query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QueryResponse Query([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] QueryRequest request) {
            object[] results = this.Invoke("Query", new object[] {
                        request});
            return ((QueryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAsync(QueryRequest request) {
            this.QueryAsync(request, null);
        }
        
        /// <remarks/>
        public void QueryAsync(QueryRequest request, object userState) {
            if ((this.QueryOperationCompleted == null)) {
                this.QueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOperationCompleted);
            }
            this.InvokeAsync("Query", new object[] {
                        request}, this.QueryOperationCompleted, userState);
        }
        
        private void OnQueryOperationCompleted(object arg) {
            if ((this.QueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCompleted(this, new QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class GetAuthorizedCredit {
        
        private string anoField;
        
        private string cavvField;
        
        private string cepField;
        
        private string complementoField;
        
        private string cpfField;
        
        private string cvc2Field;
        
        private string distribuidorField;
        
        private string eciField;
        
        private string enderecoField;
        
        private string filiacaoField;
        
        private string iataField;
        
        private string identificacaoFaturaField;
        
        private string mesField;
        
        private string nrcartaoField;
        
        private string numPedidoField;
        
        private string numeroField;
        
        private string origemField;
        
        private string parcelasField;
        
        private string portadorField;
        
        private string recorrenteField;
        
        private string senhaField;
        
        private string taxaEmbarqueField;
        
        private string totalField;
        
        private int transacaoField;
        
        private bool transacaoFieldSpecified;
        
        private string xidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cavv {
            get {
                return this.cavvField;
            }
            set {
                this.cavvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cvc2 {
            get {
                return this.cvc2Field;
            }
            set {
                this.cvc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Distribuidor {
            get {
                return this.distribuidorField;
            }
            set {
                this.distribuidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Eci {
            get {
                return this.eciField;
            }
            set {
                this.eciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filiacao {
            get {
                return this.filiacaoField;
            }
            set {
                this.filiacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Iata {
            get {
                return this.iataField;
            }
            set {
                this.iataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificacaoFatura {
            get {
                return this.identificacaoFaturaField;
            }
            set {
                this.identificacaoFaturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nrcartao {
            get {
                return this.nrcartaoField;
            }
            set {
                this.nrcartaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumPedido {
            get {
                return this.numPedidoField;
            }
            set {
                this.numPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Parcelas {
            get {
                return this.parcelasField;
            }
            set {
                this.parcelasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Portador {
            get {
                return this.portadorField;
            }
            set {
                this.portadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Recorrente {
            get {
                return this.recorrenteField;
            }
            set {
                this.recorrenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TaxaEmbarque {
            get {
                return this.taxaEmbarqueField;
            }
            set {
                this.taxaEmbarqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public int Transacao {
            get {
                return this.transacaoField;
            }
            set {
                this.transacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransacaoSpecified {
            get {
                return this.transacaoFieldSpecified;
            }
            set {
                this.transacaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Xid {
            get {
                return this.xidField;
            }
            set {
                this.xidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class ThreeDClass {
        
        private string cAVVField;
        
        private string eCIField;
        
        private string xIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CAVV {
            get {
                return this.cAVVField;
            }
            set {
                this.cAVVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ECI {
            get {
                return this.eCIField;
            }
            set {
                this.eCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string XID {
            get {
                return this.xIDField;
            }
            set {
                this.xIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class AvsQueryClass {
        
        private string cEPField;
        
        private string cOMPLEMENTOField;
        
        private string cPFField;
        
        private string eNDERECOField;
        
        private string mSG_AVSField;
        
        private string nU_ENDERECOField;
        
        private string rESP_AVSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COMPLEMENTO {
            get {
                return this.cOMPLEMENTOField;
            }
            set {
                this.cOMPLEMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ENDERECO {
            get {
                return this.eNDERECOField;
            }
            set {
                this.eNDERECOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MSG_AVS {
            get {
                return this.mSG_AVSField;
            }
            set {
                this.mSG_AVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NU_ENDERECO {
            get {
                return this.nU_ENDERECOField;
            }
            set {
                this.nU_ENDERECOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RESP_AVS {
            get {
                return this.rESP_AVSField;
            }
            set {
                this.rESP_AVSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class RegistroClass {
        
        private AvsQueryClass aVSField;
        
        private string cOD_RETField;
        
        private string dATAField;
        
        private string dATA_CANCField;
        
        private string dATA_CON_PRE_AUTField;
        
        private string dATA_EXP_PRE_AUTField;
        
        private string fILIACAO_DSTRField;
        
        private string hORAField;
        
        private string iDENTIFICACAOFATURAField;
        
        private string mOEDAField;
        
        private string mSG_RETField;
        
        private string nOM_PORTADORField;
        
        private string nR_CARTAOField;
        
        private string nUMAUTORField;
        
        private string nUMPEDIDOField;
        
        private string nUMSQNField;
        
        private string oRIGEMField;
        
        private string pARCELASField;
        
        private string sTATUSField;
        
        private string tAXA_EMBARQUEField;
        
        private string tIDField;
        
        private string tOTALField;
        
        private string tRANSACAOField;
        
        private ThreeDClass item3DSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AvsQueryClass AVS {
            get {
                return this.aVSField;
            }
            set {
                this.aVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COD_RET {
            get {
                return this.cOD_RETField;
            }
            set {
                this.cOD_RETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATA_CANC {
            get {
                return this.dATA_CANCField;
            }
            set {
                this.dATA_CANCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATA_CON_PRE_AUT {
            get {
                return this.dATA_CON_PRE_AUTField;
            }
            set {
                this.dATA_CON_PRE_AUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATA_EXP_PRE_AUT {
            get {
                return this.dATA_EXP_PRE_AUTField;
            }
            set {
                this.dATA_EXP_PRE_AUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FILIACAO_DSTR {
            get {
                return this.fILIACAO_DSTRField;
            }
            set {
                this.fILIACAO_DSTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HORA {
            get {
                return this.hORAField;
            }
            set {
                this.hORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDENTIFICACAOFATURA {
            get {
                return this.iDENTIFICACAOFATURAField;
            }
            set {
                this.iDENTIFICACAOFATURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOEDA {
            get {
                return this.mOEDAField;
            }
            set {
                this.mOEDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MSG_RET {
            get {
                return this.mSG_RETField;
            }
            set {
                this.mSG_RETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOM_PORTADOR {
            get {
                return this.nOM_PORTADORField;
            }
            set {
                this.nOM_PORTADORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NR_CARTAO {
            get {
                return this.nR_CARTAOField;
            }
            set {
                this.nR_CARTAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NUMAUTOR {
            get {
                return this.nUMAUTORField;
            }
            set {
                this.nUMAUTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NUMPEDIDO {
            get {
                return this.nUMPEDIDOField;
            }
            set {
                this.nUMPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NUMSQN {
            get {
                return this.nUMSQNField;
            }
            set {
                this.nUMSQNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORIGEM {
            get {
                return this.oRIGEMField;
            }
            set {
                this.oRIGEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PARCELAS {
            get {
                return this.pARCELASField;
            }
            set {
                this.pARCELASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TAXA_EMBARQUE {
            get {
                return this.tAXA_EMBARQUEField;
            }
            set {
                this.tAXA_EMBARQUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRANSACAO {
            get {
                return this.tRANSACAOField;
            }
            set {
                this.tRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("3DS", IsNullable=true)]
        public ThreeDClass Item3DS {
            get {
                return this.item3DSField;
            }
            set {
                this.item3DSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class HeaderClass {
        
        private string dATA_REQUISICAOField;
        
        private string fILIACAOField;
        
        private string hORA_REQUISICAOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DATA_REQUISICAO {
            get {
                return this.dATA_REQUISICAOField;
            }
            set {
                this.dATA_REQUISICAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FILIACAO {
            get {
                return this.fILIACAOField;
            }
            set {
                this.fILIACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HORA_REQUISICAO {
            get {
                return this.hORA_REQUISICAOField;
            }
            set {
                this.hORA_REQUISICAOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class QueryResponse {
        
        private HeaderClass hEADERField;
        
        private RegistroClass rEGISTROField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public HeaderClass HEADER {
            get {
                return this.hEADERField;
            }
            set {
                this.hEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RegistroClass REGISTRO {
            get {
                return this.rEGISTROField;
            }
            set {
                this.rEGISTROField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class QueryRequest {
        
        private string filiacaoField;
        
        private string numPedidoField;
        
        private string senhaField;
        
        private string tidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filiacao {
            get {
                return this.filiacaoField;
            }
            set {
                this.filiacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumPedido {
            get {
                return this.numPedidoField;
            }
            set {
                this.numPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class ConfirmTxnTID {
        
        private string dataField;
        
        private string filiacaoField;
        
        private string numAutorField;
        
        private string numSqnField;
        
        private string parcelasField;
        
        private string senhaField;
        
        private string tidField;
        
        private string totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filiacao {
            get {
                return this.filiacaoField;
            }
            set {
                this.filiacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumAutor {
            get {
                return this.numAutorField;
            }
            set {
                this.numAutorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumSqn {
            get {
                return this.numSqnField;
            }
            set {
                this.numSqnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Parcelas {
            get {
                return this.parcelasField;
            }
            set {
                this.parcelasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class Confirmation {
        
        private string codRetField;
        
        private string dataField;
        
        private string horaField;
        
        private string msgRetField;
        
        private string numSqnField;
        
        private string tidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodRet {
            get {
                return this.codRetField;
            }
            set {
                this.codRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgRet {
            get {
                return this.msgRetField;
            }
            set {
                this.msgRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumSqn {
            get {
                return this.numSqnField;
            }
            set {
                this.numSqnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class VoidTransactionTID {
        
        private string dataField;
        
        private string filiacaoField;
        
        private string numAutorField;
        
        private string numSqnField;
        
        private string senhaField;
        
        private string tidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filiacao {
            get {
                return this.filiacaoField;
            }
            set {
                this.filiacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumAutor {
            get {
                return this.numAutorField;
            }
            set {
                this.numAutorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumSqn {
            get {
                return this.numSqnField;
            }
            set {
                this.numSqnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class Authorization {
        
        private string codRetField;
        
        private string dataField;
        
        private string horaField;
        
        private string msgAvsField;
        
        private string msgretField;
        
        private string numAutorField;
        
        private string numPedidoField;
        
        private string numSqnField;
        
        private string respAvsField;
        
        private string tidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodRet {
            get {
                return this.codRetField;
            }
            set {
                this.codRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgAvs {
            get {
                return this.msgAvsField;
            }
            set {
                this.msgAvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Msgret {
            get {
                return this.msgretField;
            }
            set {
                this.msgretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumAutor {
            get {
                return this.numAutorField;
            }
            set {
                this.numAutorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumPedido {
            get {
                return this.numPedidoField;
            }
            set {
                this.numPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumSqn {
            get {
                return this.numSqnField;
            }
            set {
                this.numSqnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RespAvs {
            get {
                return this.respAvsField;
            }
            set {
                this.respAvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class GetAuthorizedDebit {
        
        private string anoField;
        
        private string cavvField;
        
        private string cepField;
        
        private string complementoField;
        
        private string cpfField;
        
        private string cvc2Field;
        
        private string distribuidorField;
        
        private string eciField;
        
        private string enderecoField;
        
        private string filiacaoField;
        
        private string iataField;
        
        private string identificacaoFaturaField;
        
        private string mesField;
        
        private string nrcartaoField;
        
        private string numPedidoField;
        
        private string numeroField;
        
        private string origemField;
        
        private string parcelasField;
        
        private string portadorField;
        
        private string senhaField;
        
        private string taxaEmbarqueField;
        
        private string totalField;
        
        private int transacaoField;
        
        private bool transacaoFieldSpecified;
        
        private string xidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cavv {
            get {
                return this.cavvField;
            }
            set {
                this.cavvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cvc2 {
            get {
                return this.cvc2Field;
            }
            set {
                this.cvc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Distribuidor {
            get {
                return this.distribuidorField;
            }
            set {
                this.distribuidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Eci {
            get {
                return this.eciField;
            }
            set {
                this.eciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filiacao {
            get {
                return this.filiacaoField;
            }
            set {
                this.filiacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Iata {
            get {
                return this.iataField;
            }
            set {
                this.iataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificacaoFatura {
            get {
                return this.identificacaoFaturaField;
            }
            set {
                this.identificacaoFaturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nrcartao {
            get {
                return this.nrcartaoField;
            }
            set {
                this.nrcartaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumPedido {
            get {
                return this.numPedidoField;
            }
            set {
                this.numPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Parcelas {
            get {
                return this.parcelasField;
            }
            set {
                this.parcelasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Portador {
            get {
                return this.portadorField;
            }
            set {
                this.portadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TaxaEmbarque {
            get {
                return this.taxaEmbarqueField;
            }
            set {
                this.taxaEmbarqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public int Transacao {
            get {
                return this.transacaoField;
            }
            set {
                this.transacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransacaoSpecified {
            get {
                return this.transacaoFieldSpecified;
            }
            set {
                this.transacaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Xid {
            get {
                return this.xidField;
            }
            set {
                this.xidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class CreditAuthorizationResponse {
        
        private string cetField;
        
        private string codRetField;
        
        private string dataField;
        
        private string horaField;
        
        private string jurosField;
        
        private string msgAvsField;
        
        private string msgretField;
        
        private string numAutorField;
        
        private string numPedidoField;
        
        private string numSqnField;
        
        private string respAvsField;
        
        private string tidField;
        
        private string valParcelasField;
        
        private string valTotalJurosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cet {
            get {
                return this.cetField;
            }
            set {
                this.cetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodRet {
            get {
                return this.codRetField;
            }
            set {
                this.codRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Juros {
            get {
                return this.jurosField;
            }
            set {
                this.jurosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgAvs {
            get {
                return this.msgAvsField;
            }
            set {
                this.msgAvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Msgret {
            get {
                return this.msgretField;
            }
            set {
                this.msgretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumAutor {
            get {
                return this.numAutorField;
            }
            set {
                this.numAutorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumPedido {
            get {
                return this.numPedidoField;
            }
            set {
                this.numPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumSqn {
            get {
                return this.numSqnField;
            }
            set {
                this.numSqnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RespAvs {
            get {
                return this.respAvsField;
            }
            set {
                this.respAvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ValParcelas {
            get {
                return this.valParcelasField;
            }
            set {
                this.valParcelasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ValTotalJuros {
            get {
                return this.valTotalJurosField;
            }
            set {
                this.valTotalJurosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetAuthorizedCreditCompletedEventHandler(object sender, GetAuthorizedCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorizedCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorizedCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditAuthorizationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditAuthorizationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetAuthorizedDebitCompletedEventHandler(object sender, GetAuthorizedDebitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorizedDebitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorizedDebitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Authorization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Authorization)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void VoidTransactionTIDCompletedEventHandler(object sender, VoidTransactionTIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoidTransactionTIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoidTransactionTIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Confirmation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Confirmation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConfirmTxnTIDCompletedEventHandler(object sender, ConfirmTxnTIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmTxnTIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmTxnTIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Authorization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Authorization)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void QueryCompletedEventHandler(object sender, QueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591